#!/bin/env bash

# This script is heavily based on:
# http://giovannitorres.me/create-a-linux-lab-on-kvm-using-cloud-images.html
# and is intended to consume a qcow2 image from:
# https://cloud.centos.org/centos/7/images/

### VARIABLES
# option defaults
e="hostname"   # hostname
o="home.local" # domain
i=""           # ip, intentionally left blank
d="8"          # disk size, in GB. 8GB is the minimum as I have not yet written shrinking.
m="512"        # memory quantity, in MB
c="1"          # cpu count
u="mudkip"     # username to add
               # below: ssh key for user
s="ssh-rsa THISISNOTAREALHASHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHVAMPIRESSUCK"
a="y"          # sudo access, y/n
# others
template="/full/path/to/CentOS-7-x86_64-GenericCloud-1711.qcow2"
                                     # above: template path
image_path="/var/lib/libvirt/images" # the path to where we store our vm qcow2 images
net_prefix="192.168.0."              # the /24 non-cidr prefix for a network you provision to
net_firstaddr="100"                  # the first value of the last octet of our /24
net_lastaddr="200"                   # the last value of the last octet of our /24
bridge="br0"                         # bridge interface (assuming bridged networking)
provision_timeout="30"               # provisioning timeout in seconds

### FUNCTIONS
function parse_args() {
  local OPTIND v
  while getopts ":e:o:i:d:m:c:u:s:a" v; do
    case ${v} in
      e)
       #hostname
       e=${OPTARG}
       ;;
      o)
       #domain
       o=${OPTARG}
       ;;
      i)
       #ip
       i=${OPTARG}
       ;;
      d)
       #disk
       [ ${OPTARG} -lt 8 ] && ${OPTARG}=8
       d=${OPTARG}
       ;;
      m)
       #memory
       m=${OPTARG}
       ;;
      c)
       #cpu
       c=${OPTARG}
       ;;
      u)
       #username
       u=${OPTARG}
       ;;
      s)
       #ssh key
       s=${OPTARG}
       ;;
      a)
       #sudo
       [[ "${OPTARG}" =~ ^[YyNn]$ ]] || { echo "Invalid option value"; exit 1; }
       a=$(echo "${OPTARG}" | $trbin [:upper:] [:lower:])
       ;;
      *)
       show_help
       ;;
    esac
  done
  [ "${i}" == "" ] && i=$(get_unused_netaddr)
}

function get_confirmation() {
  local z=""
  read -e -p "$@ (y|n)[y]: " z
  [[ "${z}" =~ ^[YyNn]$ ]] || z='y'
  [[ "${z}" =~ ^[Yy]$ ]] && return 0 || return 1
}

function get_input() {
  local v=""
  local d="$2"
  local dd=$d
  local m="$1"
  [ ${#d} -gt 16 ] && dd="${d:0:16}..."
  read -e -p "${m} [${dd}]: " v
  if [ ! -z "${v}" ]; then
    if [[ "${v}" =~ ^\s{1,}$ ]]; then
      echo $d
    else
      echo $v
    fi
  else
    echo $d
  fi
}

function ensure_requirements() {
  whichbin=$(which which >/dev/null 2>&1 || { echo "This script requires 'which'. Please install and re-run."; exit 1; })
  for b in virt-filesystems virt-resize qemu-img df virt-install genisoimage tee date tr virsh touch shuf ping; do
    which ${b} >/dev/null 2>&1 || { echo "This script requires '${b}'. Please install and re-run."; exit 1; }
  done
  setbins
  [ -f ${template} ] || { echo "Disk template '${template}' not found. Please ensure this is available and re-run."; exit 1; }
  [ -d ${image_path} ] && {
    $touchbin "${image_path}/.write_test" 2>/dev/null || { echo "Unable to write to image path '${image_path}'. Please correct permissions and re-run."; exit 1; }
  } || {
    echo "Unable to find image path '${image_path}'. Please ensure it exists and re-run."; exit 1;
  } && rm -f "${image_path}/.write_test"
}

function setbins() {
  virshbin=$(which virsh)
  touchbin=$(which touch)
  shufbin=$(which shuf)
  pingbin=$(which ping)
  trbin=$(which tr)
  datebin=$(which date)
  teebin=$(which tee)
  genisoimagebin=$(which genisoimage)
  virtinstallbin=$(which virt-install)
  dfbin=$(which df)
  qemuimgbin=$(which qemu-img)
  virtresizebin=$(which virt-resize)
  virtfilesystemsbin=$(which virt-filesystems)
}

function get_unused_netaddr() {
  local retval=0
  while [ $retval -ne 1 ]; do
    local r=$(${shufbin} -i ${net_firstaddr}-${net_lastaddr} -n 1)
    local n="${net_prefix}${r}"
    ${pingbin} -c 1 -w 1 ${n} >/dev/null 2>&1
    local retval=$?
  done
  echo $n
}

function interactive_start() {
  local v=""
  local n=$(get_unused_netaddr)
  e=$(get_input "Hostname" "${e}")
  o=$(get_input "DNS Domain" "${o}")
  i=$(get_input "IP" "${n}")
  d=$(get_input "Disk (GB)" "${d}")
  m=$(get_input "Memory (MB)" "${m}")
  c=$(get_input "CPUs" "${c}")
  u=$(get_input "Username" "${u}")
  s=$(get_input "SSH Key" "${s}")
  get_confirmation "Sudo?" && a='y' || a='n'
}

function show_help() {
  echo
  echo 'NAME'
  echo '  create_vm - creates a new libvirt vm from a series of options'
  echo
  echo 'DESCRIPTION'
  echo '  This is a highly modified version of http://giovannitorres.me/create-a-linux-lab-on-kvm-using-cloud-images.html'
  echo '  create_vm can also be ran interactively by not supplying any args.'
  echo
  echo 'Usage:'
  echo '  create_vm [OPTION] <ARG>'
  echo
  echo '  Options:'
  echo '    -e <shortname>             the short hostname for the new server'
  echo '    -o <dns domain>            the dns domain for the new server'
  echo "    -i <ip>                    the IP you'd like provisioned. if you do not provide an IP a random IP will be"
  echo '                                 generated for you and suggested during the presentation of the VM details'
  echo "    -d <disk size>             the disk size (in GB) you'd like to increase or decrease your image to"
  echo '    -m <memory quantity>       the quantity of memory assigned to this machine, in MB'
  echo '    -c <cpu count>             the number of cpus assigned to this vm'
  echo "    -u <username>              the username you'd like to add on provision"
  echo '    -s <ssh key>               the ssh key to add for authentication on the provisioned user'
  echo '    -a (y|n)                   whether to grant sudo access to the provisioned user'
  echo
  exit 1
}

function display_new_vm_info() {
  echo
  echo 'NEW VM:'
  echo '-------------------'
  echo "Hostname:     $e"
  echo "DNS Domain:   $o"
  echo "IP:           $i"
  echo "Disk:         ${d}GB"
  echo "Memory:       ${m}MB"
  echo "CPUs:         $c"
  echo
  echo 'ADD USER'
  echo '-------------------'
  echo "Username:     $u"
  echo "SSH Key:      ${s:0:16}..."
  echo "Sudo enabled? $a"
  echo
}

function confirm_start() {
  get_confirmation 'Does the above look correct?' || {
    echo "Exiting on user input..."
    exit 2
  }
}

function check_for_overwrite() {
  $virshbin dominfo ${e} >/dev/null 2>&1 && {
    get_confirmation "VM '${e}' already exists. Overwrite?" || {
      echo "Exiting on user input..."
      exit 2
    } && overwrite='y'
  }
}

function log() {
  # log to the log file. can't be used until after log_file is defined.
  echo "$(date +"%Y%m%d:%T") // ${@}" | ${teebin} -a ${log_file}
}

function nuke_and_pave() {
  [ "${overwrite}" == 'y' ] && {
    log "Destroying the '${e}' domain..."
    rm -rf ${image_path}
    mkdir -p ${image_path}
    $virshbin destroy "${e}" 2>&1 >> ${log_file}
    $virshbin undefine "${e}" 2>&1 >> ${log_file}
  } ||  mkdir -p ${image_path}
  log "Creating ${image_path}"
}

function write_user_data() {
  log "Writing user_data to '${user_data}'"
  cat > ${user_data} << _EOF_
#cloud-config

# Hostname management
preserve_hostname: False
hostname: ${e}
fqdn: ${e}.${o}

# Remove cloud-init when finished with it and write our network config out
runcmd:
  - [ yum, -y, remove, cloud-init ]
  - xfs_growfs /dev/vda1
  - sed -i '/IPADDR/d' /etc/sysconfig/network-scripts/ifcfg-eth0
  - echo "IPADDR=${i}" >> /etc/sysconfig/network-scripts/ifcfg-eth0
  - /sbin/service network restart

# Configure where output will go
output:
  all: ">> /var/log/cloud-init.log"

# configure interaction with ssh server
ssh_svcname: ssh
ssh_deletekeys: True
ssh_genkeytypes: ['rsa', 'ecdsa']

# Install my public ssh key to the first user-defined user configured
# in cloud.cfg in the template
ssh_authorized_keys:
  - ${s}

# Setup resolv.conf
manage_resolv_conf: true
resolv_conf:
  nameservers: ['192.168.0.3']
  searchdomains:
    - solarsquid.local
  domain: solarsquid.local
_EOF_
}

function write_meta_data() {
  log "Writing meta data to '${meta_data}'"
  echo -e "instance-id: ${e}\nlocal-hostname: ${e}" > ${meta_data}
}

function copy_template_to_image_and_resize() {
  log "Copying template image '${template}' to '${image}' and expanding to ${d}GB..."
  ${qemuimgbin} create -f qcow2 -o preallocation=metadata ${image} ${d}G 2>&1 >> ${log_file}
  local fs=$(${virtfilesystemsbin} --long -h --all -a ${template} | grep partition | awk '{ print $1 }')
  ${virtresizebin} --expand ${fs} ${template} ${image} 2>&1 >> ${log_file}
}

function create_iso_for_cloud_init() {
  log "Generating ISO for cloud-init with the following params:"
  cmd="${genisoimagebin} -output ${ci_iso} -volid cidata -joliet -r ${user_data} ${meta_data}"
  log "  '${cmd}'"
  eval "${cmd}" 2>&1 >> ${log_file}
}

function create_vm() {
  log "Installing the domain and adjusting the configuration with the following params:"
  cmd="${virtinstallbin} --import --name ${e} --ram ${m} --vcpus ${c} --disk ${image},format=qcow2,bus=virtio --disk ${ci_iso},device=cdrom --network bridge=${bridge},model=virtio --os-type=linux --os-variant=rhel7 --noautoconsole"
  log "  '${cmd}'"
  eval "${cmd}" 2>&1 >> ${log_file}
}

function wait_for_start() {
  log "Pausing for provision (max ${provision_timeout}s)"
  local c=0; 
  while [ $c -lt ${provision_timeout} ]; do
    ping -c 1 -w 1 ${i} >/dev/null 2>&1 && { break; } 
    local c=$((${c}+1))
  done
  [ $c -eq ${provision_timeout} ] && { log "** Timeout, exiting. Check network config to ensure ability to ping ${i}."; }
  log '** done'
}

function clean_up_cloud_init() {
  log "Cleaning up cloud-init"
  virsh change-media ${e} hda --eject --config 2>&1 >> ${log_file}
  rm -v ${user_data} ${ci_iso} 2>&1 >> ${log_file}
}

function check_for_free_space() {
  log "Checking for available free space"
  local availbytes=$(${dfbin} ${image_path} | awk '{ print $4 }' | tail -n 1)
  # 1073741824 bytes in 1 gb
  local neededbytes=$((((${d}*1000)*1000)))
  [ ${neededbytes} -ge ${availbytes} ] && { log "Size (${neededbytes}) exceeds available space (${availbytes}), unable to continue."; exit 1; }
}

### MAIN
# error handling
trap "exit 1" TERM
export TOP_PID=$$

ensure_requirements

[ $# -eq 0 ] && interactive_start || parse_args $@

# print info and confirm this is what we want
display_new_vm_info
confirm_start

# set some other vars we need
image_path="${image_path}/${e}"
user_data="${image_path}/user-data"
meta_data="${image_path}/meta-data"
ci_iso="${image_path}/${e}-cidata.iso"
image="${image_path}/${e}.qcow2"
log_file="${image_path}/${e}.log"

check_for_overwrite
nuke_and_pave
write_user_data
write_meta_data
check_for_free_space
copy_template_to_image_and_resize
create_iso_for_cloud_init
create_vm
wait_for_start
clean_up_cloud_init

log "All done. SSH to your new VM at '${i}'"
echo
